[package]
name = "module-evm-rpc-runtime-api"
version = "0.1.0"
authors = ["Bitgreen Developers"]
edition = "2018"

[dependencies]
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.19" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.19" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.19" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.19" }
ethereum-types = { version = "0.11.0", default-features = false }
primitives = { package = "bitg-primitives", path = "../../../../primitives", default-features = false }

[features]
default = ["std"]
std = [
	"sp-runtime/std",
	"sp-api/std",
	"sp-std/std",
	"sp-core/std",
	"ethereum-types/std",
	"primitives/std",
]
